# Generated by Django 3.2.4 on 2021-06-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True, null=True)),
                ('url', models.TextField()),
                ('date_posted', models.DateField()),
                ('description', models.TextField(default='')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
