# Generated by Django 3.2.4 on 2021-06-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True, null=True)),
                ('url', models.TextField(primary_key=True, serialize=False)),
                ('date_posted', models.DateField()),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('fb', 'facebook'), ('reddit', 'reddit')], max_length=50)),
            ],
        ),
    ]
